2025-03-19 14:56:45,405 INFO    MainThread:3197870 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-19 14:56:45,405 INFO    MainThread:3197870 [wandb_setup.py:_flush():67] Configure stats pid to 3197870
2025-03-19 14:56:45,405 INFO    MainThread:3197870 [wandb_setup.py:_flush():67] Loading settings from /home/ryuichi/.config/wandb/settings
2025-03-19 14:56:45,406 INFO    MainThread:3197870 [wandb_setup.py:_flush():67] Loading settings from /home/ryuichi/tree/TREE_PROJ/wandb/settings
2025-03-19 14:56:45,406 INFO    MainThread:3197870 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-19 14:56:45,406 INFO    MainThread:3197870 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/ryuichi/tree/TREE_PROJ/wandb/run-20250319_145645-6u62olj2/logs/debug.log
2025-03-19 14:56:45,406 INFO    MainThread:3197870 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/ryuichi/tree/TREE_PROJ/wandb/run-20250319_145645-6u62olj2/logs/debug-internal.log
2025-03-19 14:56:45,406 INFO    MainThread:3197870 [wandb_init.py:init():761] calling init triggers
2025-03-19 14:56:45,406 INFO    MainThread:3197870 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'epochs': 1, 'batch_size': 16, 'learning_rate': 0.001, 'device': 'cuda', 'architecture': 'SVSAE', 'dataset_size': None, 'loss_weights': {'mse': 1.0, 'iou': 0.5, 'chamfer': 0.5}, '_wandb': {}}
2025-03-19 14:56:45,406 INFO    MainThread:3197870 [wandb_init.py:init():784] starting backend
2025-03-19 14:56:45,406 INFO    MainThread:3197870 [wandb_init.py:init():788] sending inform_init request
2025-03-19 14:56:45,413 INFO    MainThread:3197870 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-19 14:56:45,414 INFO    MainThread:3197870 [wandb_init.py:init():803] backend started and connected
2025-03-19 14:56:45,416 INFO    MainThread:3197870 [wandb_init.py:init():896] updated telemetry
2025-03-19 14:56:45,423 INFO    MainThread:3197870 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-19 14:56:45,825 INFO    MainThread:3197870 [wandb_init.py:init():995] starting run threads in backend
2025-03-19 14:56:45,913 INFO    MainThread:3197870 [wandb_run.py:_console_start():2377] atexit reg
2025-03-19 14:56:45,914 INFO    MainThread:3197870 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-19 14:56:45,914 INFO    MainThread:3197870 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-19 14:56:45,914 INFO    MainThread:3197870 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-19 14:56:45,917 INFO    MainThread:3197870 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-19 15:08:48,548 WARNING MsgRouterThr:3197870 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/ryuichi/anaconda3/envs/tree/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/home/ryuichi/anaconda3/envs/tree/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/home/ryuichi/anaconda3/envs/tree/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ryuichi/anaconda3/envs/tree/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/home/ryuichi/anaconda3/envs/tree/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-19 15:08:48,549 INFO    MsgRouterThr:3197870 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
